### ISSUE TITLE
Group tasks or stages in visualization

### ISSUE THREAD

**Issue by windiana42** [pydiverse/pydiverse.pipedag#180]
It is good practice to create fine grained tasks (i.e. producing just single tables) to show the wiring of tables representing different data entities explicitly in code.
However, for visualization, it is sometimes nice to show some tasks or stages as an aggregated box or to surround them with a grouping box.

There are a few ideas how to do this. For example the grouping could be integrated in the DAG definition at Flow declare time:
```python
with Flow() as flow:
  with GroupNode(hide_box=True, hide_content=True):
    with Stage("hidden_stage"):
      ...
  with Stage("visible_stage"):
    ...
```
or
```python
with Flow() as flow:
  with Stage("stage_1"):
    with GroupNode(hide_content=False):
      a = task1()
      b = task2(a)
```

Another alternative could be that the grouping and hiding is actually configured in `pipedag.yaml` and linked with tasks via tags:
```yaml
    visualization_nodes:
      hide_stage1:  # arbitrary name/tag
        stages:
          - stage1
        style:
          hide_content: true
          hide_box: true
      surround_stages:
        label: "stage2-3"
        stages:
          - stage2
          - stage3
        style:
          box_type: "stage"
          box_color_always: "#aaaaaa"
      combine_tasks:  # tasks tagged with @materialize(tag="combine_tasks") are added to this group as well
        label: "epic effort"
        tasks:
          - task1
          - task2
        style:
          box_type: "task"
          box_color_any_failure: "#aa0000"
          box_color_none_cache_valid: "#008800"
          box_color_any_cache_valid: "#00aa00"
          box_color_all_cache_valid: "#00ff00"
          box_color_all_skipped: "#cccccc"
          hide_content: true
```

Tasks + Stages could be tagged like this:
```python
@materialize(tag="combined_tasks")
def task1():
  return pd.DataFrame(dict(a=[1]))

with Flow() as flow:
  with Stage("stage_1", tag="surround_stages"):
      a = task1()
```

VisualizationNode could have the following interface:
```python
@dataclass
class VisualizationStyle:
  hide_box = False
  hide_content = False
  hide_label = False
  box_color_always: str | None = None # takes precedence over all color settings below
  box_color_any_failure: str | None = None  # if any failure occurred within included tasks
  box_color_none_cache_valid: str | None = None  # if no failure occurred and no included task cache valid
  box_color_any_cache_valid: str | None = None  # if no failure occurred and some but not all included tasks cache valid
  box_color_all_cache_valid: str | None = None  # if no failure occurred and all included tasks cache valid
  box_color_all_skipped: str | None = None  # if no failure occurred and all included tasks were skipped
  
def GroupNode(label: str | None = None,  style: VisualizationStyle | None = None, *, ordering_barrier=False, style_tag: str|None=None)
   """label/style overwrite any values given by configuration; 
      tag matches to visualization_nodes dictionary in configuration; 
      Errors are raised if visualization_nodes section matched by GroupNode class also include tasks or stages section; 
      tags for Stages and Tasks within GroupNode block are ignored (logger.info informs about this);
      ordering_barrier=True ensures all tasks before/after group are executed before/after tasks within group""" 
```

**Comment by NicholasHoernleQC** [comment]
This would be really helpful! Thanks @windiana42. I would have the slight preference for configuration in the `pipedag.yml` so that the pipeline definition keeps to only structural definitions.

**Comment by windiana42** [comment]
@NicholasHoernleQC the proposal here is to implement both that groups can be defined as part of flow declaration and within configuration. Even a mixture would be possible. So a pure configuration based approach should be feasible.

**Comment by windiana42** [comment]
In #181 we had the idea to support `with GroupNode(ordering_barrier=True)` as a group that guarantees all tasks before the group, all within the group, and all after the group will be executed after each other. Thus I will modify the proposal above to rename `VisualizationNode` to `GroupNode` above.

**Comment by windiana42** [comment]
When using configuration to define visualization nodes and style, it might even be nice to define multiple visualizations that can be pulled from code with a name. In this case, a generic `visualization:` section might be better and we could even consider to put the kroki parameters in there:
```
visualization:
  default:
    disable_kroki: false
    group_nodes:
      hide_stage1:  # arbitrary name/tag
        stages:
          - stage1
        style:
          hide_completely: true
  alternative_visualization_full:
    disable_kroki: false
```

```python
result.flow.run()
print(result.visualize_url())
print(result.visualize_url("alternative_visualization_full"))
```

**Comment by windiana42** [comment]
Since explicit GroupNodes also want to reference styles but no group nodes, this is a proposal to seperate the two concerns in configuration:
```
visualization:
  default:
    disable_kroki: false
    styles:
      hide:
        hide_content: true
        hide_box: true
    group_nodes:
      hide_stage1:  # arbitrary name/tag
        stages:
          - stage1
        style: hide
  alternative_visualization_full:
    disable_kroki: false
```
